framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
        buses:
            messenger.bus.default:
                default_middleware: true
                middleware:
                    - doctrine_transaction_middleware

services:

    # Step 1: a factory class is registered as a service with the required
    # dependencies to instantiate a middleware
    doctrine.orm.messenger.middleware_factory.transaction:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddlewareFactory
        arguments: ['@doctrine']

    # Step 2: an abstract definition that will call the factory with default
    # arguments or the ones provided in the middleware config
    messenger.middleware.doctrine_transaction_middleware:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware
        factory: 'doctrine.orm.messenger.middleware_factory.transaction:createMiddleware'
        abstract: true
        # the default arguments to use when none provided from config. Example:
        # middleware:
        #     - doctrine_transaction_middleware: ~
        arguments: ['default']
